name: flex_yemen_v2
description: Yemen Market Modern UI
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
